name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # Triggers build only when tags like v1.0.0 are pushed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4

      -
        name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/cert-manager-webhook-vkcloud:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/cert-manager-webhook-vkcloud:${{ github.sha }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/cert-manager-webhook-vkcloud:${{ github.ref_name }}

